Repository WANTED-TEAM03/pre-onboarding-10th-4-3, pull requests merged in 2023-05, with the labels that each got.

#4 [REFACTOR] : 타입스크립트 마이그레이션
  src/App.tsx
  src/api/index.js
  src/api/index.ts
  src/api/todo.js
  src/api/todo.ts
  src/components/Header.tsx
  src/components/InputTodo.tsx
  src/components/TodoItem.tsx
  src/components/TodoList.tsx
  src/constants/config.ts
  src/hooks/useFocus.ts
  src/index.tsx
  src/pages/Main.tsx
  src/types/todo.d.ts
Labels: REFACTOR

#8 [FEAT] : 검색어 추천 기능 구현
  src/api/search.ts
  src/components/Dropdown/index.tsx
  src/components/Dropdown/styles.module.css
  src/components/DropdownItem/index.tsx
  src/components/DropdownItem/styles.module.css
  src/components/InputTodo/index.tsx
  src/components/InputTodo/styles.module.css
  src/components/TodoItem/index.tsx
  src/components/shared/LoadingSpinner/index.tsx
  src/constants/config.ts
  src/constants/search.ts
  src/hooks/useDebounce.ts
  src/hooks/useIntersectonObserver.ts
  src/hooks/useSearch.ts
  src/hooks/useToggleModal.ts
  src/pages/Main/index.tsx
  src/types/search.d.ts
  src/utils/splitTextWithKeyword.ts
Labels: FEAT

#12 [REFACTOR] : 드롭다운 깜빡임 현상 해결
  src/components/Dropdown/index.tsx
  src/components/InputTodo/index.tsx
  src/constants/search.ts
  src/hooks/useSearch.ts
Labels: REFACTOR

#14 [FEAT] : 컴포넌트 스타일 변경
  src/components/Dropdown/index.tsx
  src/components/Dropdown/styles.module.css
  src/components/DropdownItem/styles.module.css
  src/components/InputTodo/index.tsx
  src/components/shared/PlusButton/index.tsx
  src/hooks/useSearch.ts
Labels: FEAT

#16 [REFACTOR] : Todo 생성시 중복로직 제거
  src/components/InputTodo/index.tsx
Labels: REFACTOR

#18 (Task-10) README.md 작성
  README.md
  package.json
  src/components/InputTodo/index.tsx
Labels: STYLE, DOCS, CHORE

#20 테스트 코드 작성
  README.md
  babel.config.js
  jest-setup.js
  jest.config.js
  package.json
  src/__mocks__/fileMock.ts
  src/__mocks__/styleMock.ts
  src/__tests__/dropdown.test.tsx
  src/__tests__/inputTodo.test.tsx
  src/components/Dropdown/index.tsx
  src/components/DropdownItem/index.tsx
  src/components/InputTodo/index.tsx
  src/index.tsx
  tsconfig.json
Labels: TEST

#22 배포
  README.md
  babel.config.js
  jest-setup.js
  jest.config.js
  package.json
  src/__mocks__/fileMock.ts
  src/__mocks__/styleMock.ts
  src/__tests__/dropdown.test.tsx
  src/__tests__/inputTodo.test.tsx
  src/components/Dropdown/index.tsx
  src/components/DropdownItem/index.tsx
  src/components/InputTodo/index.tsx
  src/index.tsx
  tsconfig.json
Labels: RELEASE
